### PR TITLE
Add top-level severity field to exported OSV advisories

### LINKED ISSUE #781: Exported OSV advisories do not populate the top-level severity field
OSV 1.2.0 added a top-level [severity field](https://ossf.github.io/osv-schema/#severity-field), allowing to specify a CVSS as severity. RustSec currently export the CVSS under [affected[].database_specific](https://ossf.github.io/osv-schema/#affecteddatabase_specific-field): https://github.com/rustsec/rustsec/blob/2ea0ddc18551da0e906ae385dd60fc0d18ec8404/rustsec/src/osv/advisory.rs#L179

Would RustSec be open to also include the CVSS in the top-level severity field in the OSV advisories, when available? If so, I'd be happy to send a PR.

### PR DESCRIPTION
**Pull request by alpire**
Fixes #781.

OSV 1.2.0 added a top-level [severity field](https://ossf.github.io/osv-schema/#severity-field), allowing to specify a CVSS as severity. RustSec only exported the CVSS under [affected[].database_specific](https://ossf.github.io/osv-schema/#affecteddatabase_specific-field). With this PR, RustSec also populates the top-level severity field in the OSV advisories.

Example exported OSV json when severity is present, generated with `rustsec-admin osv crates`:

```json
{
  "id": "RUSTSEC-2022-0037",
  <....>
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  <...>
}
```

Example exported OSV json when severity is missing:

```json
{
  "id": "RUSTSEC-2022-0062",
  <...>
  "severity": [],
  <...>
}
```

### CODE REVIEW

**Comment by Shnatsel** [comment]
Looks good to me. This is going to be a semver version bump because this is a `pub struct`, but otherwise looks good.

@tarcieri should we add a `#[non_exhaustive]` on that struct while we're at it?

**Review by Shnatsel — APPROVED** [review]

**Comment by tarcieri** [comment]
Seems good if you expect future changes

**Comment by Shnatsel** [comment]
Oh wait, that's a private field. I'm not sure if that has any semver implications. Maybe it doesn't!

**Comment by tarcieri** [comment]
If it's private it doesn't matter

**Pull request merged**
