### PR TITLE
Revert "gix upgrade to v0.56"

### PR DESCRIPTION
**Pull request by Shnatsel**
Reverts rustsec/rustsec#1081

Seems like it caused build failures, so reverting to unblock #1092

### CODE REVIEW

**Comment by tarcieri** [comment]
cc @Byron

**Comment by Shnatsel** [comment]
Tests pass on main with gix 0.56 PR merged, so it's probably some interaction between https://github.com/rustsec/rustsec/pull/1092 and https://github.com/rustsec/rustsec/pull/1081

**Comment by Byron** [comment]
Thanks for reeling me in. In case it's something that can be fixed in `gix`, maybe you can share the build failures that are referred to?

**Comment by Shnatsel** [comment]
I've sorted it out in #1099, all good. Thanks again for your help @Byron !

**Pull request merged**
