### PR TITLE
Relax git2 requirement

### PR DESCRIPTION
**Pull request by kornelski**
Allows using git2 0.15 too

### CODE REVIEW

**Comment by alex** [comment]
is there a reason not to just upgrade to 0.15?

**Comment by tarcieri** [comment]
If it compiles with both, I think this requirement is OK.

However it would probably make sense to check it continues to compile with `-Z minimal-versions` if we do this.

**Comment by kornelski** [comment]
git2 depends on libgit2-sys that has a `links` attribute, so only one version can exist in a program. git2 versions are fragmented now, so supporting both helps: https://lib.rs/crates/git2/rev

AFAIK there aren't any real breaking changes between the two versions, so allowing both is harmless.

**Comment by tarcieri** [comment]
Cool, let's try it out

**Pull request merged**
