### PR TITLE
chore: leverage workspace inheritance

### PR DESCRIPTION
**Pull request by weihanglo**
Address <https://github.com/rustsec/rustsec/pull/1205#issuecomment-2189545101>

### CODE REVIEW

**Comment by weihanglo** [comment]
Oops the 1.40.0 MSRV is tricky

**Comment by Shnatsel** [comment]
I think we can just exclude it from the workspace, or bump MSRV if necessary because 1.40 is ancient by now.

**Comment by weihanglo** [comment]
> I think we can just exclude it from the workspace, or bump MSRV if necessary because 1.40 is ancient by now.

7d391035aa7a931ce5e559e17f090e2c94dc6fea fixes it, but I tend to do the latter. Wait a sec.

**Comment by weihanglo** [comment]
@Shnatsel are you good with 1.64? It appears that workspace inheritance was stabilized in 1.64.

https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance

**Comment by weihanglo** [comment]
Feel free to merge this as-is if <https://github.com/rustsec/rustsec/commit/7d391035aa7a931ce5e559e17f090e2c94dc6fea> is preferred.

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
