### PR TITLE
Update abscissa_core and clap

### PR DESCRIPTION
**Pull request by therealprof**
This updates abscissa_core and clap to the current versions to get rid of a few outdated dependencies.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thank you! This conversion is long overdue, and I would be very happy to see it happen.

I see some dependencies require rust 1.70, which causes CI to fail. So we also need to bump Rust toolchain version in https://github.com/rustsec/rustsec/tree/main/.github/workflows files and bump MSRV in `Cargo.toml`.

**Comment by therealprof** [comment]
@Shnatsel I've bumped the MSRV in Cargo.tomls, GHA and READMEs. I wasn't sure what to do about the CHANGELOG since there doesn't seem to be a placeholder section for the next release as of yet. 🤞🏻

**Comment by tarcieri** [comment]
Hmm, are the build failures related to #1081?

**Comment by Shnatsel** [comment]
It seems that they are. Strange, I thought CI passed before I merged it? Anyway, I'll revert it so that this PR can be merged without gix weirdness getting in the way.

**Comment by Shnatsel** [comment]
It seems there are genuine test failures in acceptance tests.

**Comment by therealprof** [comment]
I'll have a look.

**Comment by tarcieri** [comment]
Aah yeah, those were the some ones I was running into in #1068. Never figured out what the cause was. `clap` seems to be doing something weird.

**Comment by therealprof** [comment]
I can totally believe that. I had tons of problems upgrading from clap 3 to clap 4 in the past.

**Comment by therealprof** [comment]
Okay, here's the situation: I got most of the failures fixes (conflict between the automatically generated help flag and manually defined one -- don't ask me how that could produce those errors).

But:
```
thread 'version' panicked at cargo-audit/tests/acceptance.rs:207:5:
assertion `left == right` failed
  left: "cargo-audit-audit 0.18.3\n"
 right: "cargo-audit 0.18.3\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I can't for my life figure out how to override name in the version string of the `audit` subcommand. Probably would require some refactoring and it's starting to get late here, so I'm going to change the unittest for now.

**Comment by tarcieri** [comment]
@therealprof works for me. We can followup on fixing that (if possible)

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
