### PR TITLE
Semver compliant platforms

### PR DESCRIPTION
**Pull request by Shnatsel**
- Make individual platform entries `pub(crate)` (a list is still accessible through `ALL`, but platforms can be removed from it)
- Add comments on data sources and stability
- Re-export {Arch, Endian, Env, PointerWidth, OS} for prettier docs

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]

**Comment by Shnatsel** [comment]
I'm not sure if re-exporting `{Arch, Endian, Env, PointerWidth, OS}` as-is is a particularly good idea. They end up being exported twice, which is probably not ideal?

But without them on the docs.rs frontpage the docs look kinda barebones.

**Comment by Shnatsel** [comment]
Should I perhaps un-`pub` the `target` module?

**Comment by tarcieri** [comment]
Sounds good

**Comment by Shnatsel** [comment]
This does require changes in clients, but we're bumping semver anyway :shrug: 

Does this look good or should I bring `target` back?

**Comment by Shnatsel** [comment]
I decided to bring `target` back and just re-export for the enums to show up on the docs.rs frontpage.

This also simplifies migration for 2.0 users.

**Comment by tarcieri** [comment]
@Shnatsel any other changes you'd like, or should I cut a release?

**Comment by Shnatsel** [comment]
`platforms` 3.0 looks good to go, I'm not aware of any other issues with it.

**Pull request merged**
