### PR TITLE
`cargo audit bin`: filter advisories by binary type

### PR DESCRIPTION
**Pull request by Shnatsel**
Fixes https://github.com/rustsec/rustsec/issues/812

But with a pretty significant limitation of not filtering warnings, because the `rustsec` crate simply does not expose the `affected` field on warnings. So this will probably require an API break in `rustsec` to fix, one way or another.

TODO:

- [x] Figure out how to make `binfarce` an optional dependency?
- [ ] Add tests

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by amousset** [comment]
Everything that lowers the amount of false positives is good to have :+1:

**Comment by Shnatsel** [comment]
Thanks! In that case I'll add tests and merge this. 

I'll open another issue to track filtering of the warnings.

**Comment by Shnatsel** [comment]
Platform-specific advisories convenient for testing this:

https://rustsec.org/advisories/RUSTSEC-2023-0001

https://rustsec.org/advisories/RUSTSEC-2021-0119

https://rustsec.org/advisories/RUSTSEC-2022-0049.html

**Comment by Shnatsel** [comment]
I'm going to merge this to avoid future editing conflicts. I'll work on tests in a separate PR because they require large changes to the test infrastructure, which may be more controversial than this PR and require some iteration.

**Pull request merged**
